import {NextResponse} from "next/server";import {GoogleGenAI} from "@google/genai";import {createClient} from "@/lib/supabase/server";
const MODEL=process.env.GEMINI_NOTES_MODEL||"gemini-3.5-flash-lite";export const runtime="nodejs";export const maxDuration=90;
const norm=(v:string)=>v.trim().toLowerCase().replace(/\s+/g," ");
function cleanExplanation(v:string){
 return String(v||"")
  .replace(/\r/g,"")
  .replace(/^#{1,6}\s*/gm,"")
  .replace(/\*\*([^*]+)\*\*/g,"$1")
  .replace(/\*([^*]+)\*/g,"$1")
  .replace(/__([^_]+)__/g,"$1")
  .replace(/\s+$/gm,"")
  .replace(/\n{3,}/g,"\n\n")
  .trim();
}
export async function POST(request:Request){try{const s=await createClient();const {data}=await s.auth.getClaims();if(!data?.claims)return NextResponse.json({error:"Please login again."},{status:401});const {data:p}=await s.from("profiles").select("id,role,account_status").eq("id",data.claims.sub).single();if(!p||p.role!=="student"||p.account_status!=="active")return NextResponse.json({error:"Only active students can use this feature."},{status:403});const b=await request.json();const keyword=String(b.keyword||"").trim();const language=String(b.language||"English")==="Marathi"?"Marathi":"English";if(!keyword)return NextResponse.json({error:"Keyword is required."},{status:400});const {data:saved}=await s.from("study_keyword_explanations").select("explanation").eq("normalized_keyword",norm(keyword)).eq("language",language).maybeSingle();if(saved?.explanation)return NextResponse.json({ok:true,explanation:cleanExplanation(saved.explanation),cached:true});const context=String(b.context||"").trim();if(!context)return NextResponse.json({error:"Keyword context is required."},{status:400});const key=process.env.GEMINI_API_KEY;if(!key)return NextResponse.json({error:"AI service is not configured."},{status:503});const ai=new GoogleGenAI({apiKey:key});const prompt=`Explain the keyword "${keyword}" for an MPSC student in ${language}. Use ONLY the supplied published study-note context. Do not invent facts. Give a concise but detailed student-friendly explanation. Use short paragraphs and simple section labels such as "Meaning", "Key point", "MPSC relevance" and "Quick revision". Do NOT use Markdown symbols, hashtags, asterisks, bullet characters, tables, or decorative symbols. Write plain clean text with blank lines between sections. Write entirely in ${language}; retain only necessary English technical terms in parentheses. Context:\n${context}`;const r=await ai.models.generateContent({model:MODEL,contents:prompt});const explanation=cleanExplanation(r.text||"");await s.from("study_keyword_explanations").upsert({keyword,normalized_keyword:norm(keyword),language,explanation,ai_model:MODEL,updated_at:new Date().toISOString()},{onConflict:"normalized_keyword,language"});const u:any=(r as any).usageMetadata||{};await s.from("ai_usage_logs").insert({user_id:p.id,operation:"keyword_explanation_fallback",model:MODEL,status:"completed",input_tokens:Number(u.promptTokenCount||0)||null,output_tokens:Number(u.candidatesTokenCount||0)||null,total_tokens:Number(u.totalTokenCount||0)||null,completed_at:new Date().toISOString()});return NextResponse.json({ok:true,explanation,cached:false});}catch(e:any){return NextResponse.json({error:e?.message||"Could not explain keyword."},{status:500});}}