import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

export default async function AdminDashboard(){
  const supabase=await createClient();
  const {data}=await supabase.auth.getClaims();
  if(!data?.claims)redirect("/login");
  const {data:profile}=await supabase.from("profiles").select("full_name,role").eq("id",data.claims.sub).single();
  if(!profile||profile.role!=="admin")redirect("/dashboard");
  const {data:users,error}=await supabase.from("profiles").select("id,full_name,username,mobile,email,role,account_status,created_at").order("created_at",{ascending:false});
  if(error)return <div className="authWrap"><div className="card"><h2>Admin Dashboard</h2><div className="error">Unable to load users.</div></div></div>;
  const list=users??[], pending=list.filter(u=>u.account_status==="pending").length, active=list.filter(u=>u.account_status==="active").length, disabled=list.filter(u=>u.account_status==="disabled").length, rejected=list.filter(u=>u.account_status==="rejected").length;
  return <div className="shell"><header className="topbar"><div className="topbarBrand"><img src="/mpsc-logo.jpg" className="brandLogo dashboardLogo" alt="MPSC ALL-IN-ONE"/><div className="brandSub">ADMIN CONTROL CENTER</div></div><form action="/api/auth/signout" method="post"><button className="btn secondary">Logout</button></form></header><main className="main"><div className="pageHead"><div><h1>Admin Dashboard</h1><p className="muted">Welcome, {profile.full_name}. Manage registrations and system access.</p></div><a className="btn secondary" href="/dashboard">Main Dashboard</a></div><div className="stats"><div className="stat"><strong>{pending}</strong><span>Pending</span></div><div className="stat"><strong>{active}</strong><span>Active</span></div><div className="stat"><strong>{disabled}</strong><span>Disabled</span></div><div className="stat"><strong>{rejected}</strong><span>Rejected</span></div></div><section className="panel"><div className="panelHead"><div><h2>User Management</h2><p className="muted">Approve, reject, enable or disable accounts.</p></div></div><div className="tableWrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Registered</th><th>Action</th></tr></thead><tbody>{list.map(u=><tr key={u.id}><td><strong>{u.full_name}</strong><small>{u.username} · {u.mobile}</small></td><td>{u.role}</td><td><span className={"status "+u.account_status}>{u.account_status}</span></td><td>{new Date(u.created_at).toLocaleDateString("en-IN")}</td><td><div className="actions">{u.account_status==="pending"&&<><form action="/api/admin/user-status" method="post"><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="status" value="active"/><button className="btn small primary">Approve</button></form><form action="/api/admin/user-status" method="post"><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="status" value="rejected"/><button className="btn small danger">Reject</button></form></>}{u.account_status==="active"&&u.id!==data.claims.sub&&<form action="/api/admin/user-status" method="post"><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="status" value="disabled"/><button className="btn small secondary">Disable</button></form>}{u.account_status==="disabled"&&<form action="/api/admin/user-status" method="post"><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="status" value="active"/><button className="btn small primary">Enable</button></form>}{u.account_status==="rejected"&&<form action="/api/admin/user-status" method="post"><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="status" value="pending"/><button className="btn small secondary">Reopen</button></form>}</div></td></tr>)}</tbody></table></div></section></main></div>;
}