"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Block={type:string;text?:string;items?:string[];html?:string};
type Topic={id:string;title:string;notes:string;content_blocks:Block[];status:string;subject_id:string};
type Subject={id:string;subject_name:string;stage:string;paper:string;status:string;topics:Topic[]};

function esc(v:any){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function blocksToHtml(blocks:Block[]){return blocks.map((b:any)=>b.type==="richtext"&&b.html?b.html:b.type==="heading"?'<h2>'+esc(b.text)+'</h2>':b.type==="subheading"?'<h3>'+esc(b.text)+'</h3>':b.type==="bullet"?'<ul>'+(b.items||[]).map((x:string)=>'<li>'+esc(x)+'</li>').join("")+'</ul>':b.type==="numbered"?'<ol>'+(b.items||[]).map((x:string)=>'<li>'+esc(x)+'</li>').join("")+'</ol>':b.type==="callout"?'<blockquote>'+esc(b.text)+'</blockquote>':b.text?'<p>'+esc(b.text)+'</p>':"").join("")}

export default function StudyStudio(){
 const [subject,setSubject]=useState(""),[stage,setStage]=useState("Mains"),[paper,setPaper]=useState("GS Paper IV"),[topicTitle,setTopicTitle]=useState(""),[file,setFile]=useState<File|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[topic,setTopic]=useState<Topic|null>(null),[subjects,setSubjects]=useState<Subject[]>([]),[editing,setEditing]=useState(true),[preview,setPreview]=useState(false);
 const editor=useRef<HTMLDivElement>(null);
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data:subs}=await s.from("study_subjects").select("id,subject_name,stage,paper,status").eq("created_by",user.id).eq("content_area","teacher").order("created_at",{ascending:false});const ids=(subs||[]).map(x=>x.id);if(!ids.length){setSubjects([]);return;}const {data:tops}=await s.from("study_topics").select("id,subject_id,title,notes,content_blocks,status").in("subject_id",ids).order("sort_order");const grouped=new Map<string,Topic[]>();for(const t of(tops||[])){const a=grouped.get(t.subject_id)||[];a.push(t as Topic);grouped.set(t.subject_id,a)}setSubjects((subs||[]).map(s=>({...s,topics:grouped.get(s.id)||[]})) as Subject[])}
 useEffect(()=>{load()},[]);
 function openTopic(t:Topic){setTopic(t);setTopicTitle(t.title);setSubject(subjects.find(s=>s.id===t.subject_id)?.subject_name||"");setEditing(false);setTimeout(()=>{if(editor.current)editor.current.innerHTML=blocksToHtml(t.content_blocks||[])},0);setError("");setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 function format(cmd:string,value?:string){editor.current?.focus();document.execCommand(cmd,false,value)}
 function sanitizePastedHtml(input:string){
  const doc=new DOMParser().parseFromString(input,"text/html");
  const allowed=new Set(["P","BR","DIV","SPAN","H1","H2","H3","H4","STRONG","B","EM","I","U","UL","OL","LI","BLOCKQUOTE","A","FONT"]);
  const styles=new Set(["color","background-color","font-family","font-size","font-weight","font-style","text-decoration","text-align"]);
  const walk=(el:Element)=>{
   Array.from(el.children).forEach(walk);
   if(!allowed.has(el.tagName)){el.replaceWith(...Array.from(el.childNodes));return;}
   Array.from(el.attributes).forEach(a=>{
    const n=a.name.toLowerCase();
    if(n.startsWith("on")||n==="class"||n==="id"||n==="contenteditable"||n==="style"&&false)el.removeAttribute(a.name);
   });
   if(el.hasAttribute("style")){const safe=Array.from(el.getAttribute("style")!.split(";")).map(x=>x.trim()).filter(Boolean).filter(x=>styles.has(x.split(":")[0].trim().toLowerCase())).join("; ");safe?el.setAttribute("style",safe):el.removeAttribute("style");}
   if(el.tagName==="A"){const href=el.getAttribute("href")||"";if(!/^(https?:|mailto:)/i.test(href))el.removeAttribute("href");else{el.setAttribute("target","_blank");el.setAttribute("rel","noopener noreferrer");}}
  };
  Array.from(doc.body.children).forEach(walk);return doc.body.innerHTML;
 }
 function handlePaste(e:React.ClipboardEvent<HTMLDivElement>){
  if(!editing)return;
  const html=e.clipboardData.getData("text/html");
  if(html){e.preventDefault();editor.current?.focus();document.execCommand("insertHTML",false,sanitizePastedHtml(html));return;}
  const text=e.clipboardData.getData("text/plain");
  if(text){e.preventDefault();editor.current?.focus();const safe=text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").split("\r\n").join("<br>").split("\n").join("<br>");document.execCommand("insertHTML",false,safe);}
 }
 async function importPdf(){if(!subject.trim()||!topicTitle.trim()||!file){setError("Enter subject, topic and select a PDF.");return}if(file.size>50*1024*1024){setError("PDF must be 50 MB or smaller.");return}setBusy(true);setError("");setMessage("");try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("Please login again.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=user.id+"/"+crypto.randomUUID()+"-"+safe;const {error:u}=await s.storage.from("study-sources").upload(path,file,{contentType:"application/pdf",upsert:false});if(u)throw new Error("Source upload failed: "+u.message);const form=new FormData();form.append("subject",subject);form.append("stage",stage);form.append("paper",paper);form.append("topicTitle",topicTitle);form.append("sourcePath",path);form.append("sourceName",file.name);const r=await fetch("/api/teacher/study-studio/import",{method:"POST",body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||"Import failed.");setTopic({id:d.topicId,subject_id:d.subjectId,title:topicTitle,notes:"",content_blocks:d.blocks||[],status:"draft"});setEditing(true);setFile(null);setMessage("PDF imported. Format the complete material in one editor.");setTimeout(()=>{if(editor.current)editor.current.innerHTML=blocksToHtml(d.blocks||[])},0);await load()}catch(e:any){setError(e.message||"Import failed")}finally{setBusy(false)}}
 function html(){return editor.current?.innerHTML||""}
 async function saveDraft(){if(!topic)return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/teacher/study-studio/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId:topic.id,title:topicTitle,content_html:html()})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed.");setTopic({...topic,...d.topic});setEditing(false);setMessage("Saved to Drafts. Students cannot see it yet.");await load()}catch(e:any){setError(e.message||"Could not save")}finally{setBusy(false)}}
 async function publish(){if(!topic)return;if(!html().trim()){setError("Editor is empty.");return}await saveDraft();if(!confirm("Publish this material to students?"))return;setBusy(true);try{const r=await fetch("/api/teacher/study-studio/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId:topic.id,action:"publish"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Publish failed.");setTopic(t=>t?{...t,status:"published"}:t);setMessage("Published successfully to students.");await load()}catch(e:any){setError(e.message||"Could not publish")}finally{setBusy(false)}}
 const Tool=({label,cmd,value}:{label:string;cmd:string;value?:string})=><button type="button" className="btn secondary small" title={label} onMouseDown={e=>e.preventDefault()} onClick={()=>format(cmd,value)}>{label}</button>;
 return <div className="shell"><header className="topbar"><div className="topbarBrand"><img src="/mpsc-logo.png" className="brandLogo dashboardLogo" alt="MPSC ALL-IN-ONE"/><div className="brandSub">STUDY MATERIAL STUDIO</div></div><Link className="btn secondary" href="/teacher">Back</Link></header><main className="main">
 <section className="dashboardHero"><div style={{fontSize:12,fontWeight:800}}>TEACHER CONTENT STUDIO</div><h1 style={{margin:"6px 0",fontSize:28}}>Study Material Studio</h1><p className="muted">Upload the original PDF, then polish the complete material in one professional editor.</p></section>
 {error&&<div className="error" style={{marginBottom:14}}>{error}</div>}{message&&<div className="success" style={{marginBottom:14}}>{message}</div>}
 <section className="card"><h2>1. Upload Original PDF</h2><div className="formGrid"><label>Subject<input className="input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. Ethics"/></label><label>Stage<select className="select" value={stage} onChange={e=>setStage(e.target.value)}><option>Prelims</option><option>Mains</option></select></label><label>Paper<select className="select" value={paper} onChange={e=>setPaper(e.target.value)}><option>GS Paper I</option><option>GS Paper II</option><option>GS Paper III</option><option>GS Paper IV</option></select></label><label>Chapter / Topic<input className="input" value={topicTitle} onChange={e=>setTopicTitle(e.target.value)} placeholder="e.g. Introduction to Ethics"/></label></div><input type="file" accept=".pdf,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} style={{marginTop:14}}/>{file&&<div className="success" style={{marginTop:10}}>✓ {file.name}</div>}<button className="btn primary" style={{marginTop:12}} onClick={importPdf} disabled={busy||!file}>{busy?"IMPORTING…":"UPLOAD & OPEN EDITOR"}</button></section>
 {topic&&<section className="card"><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{marginBottom:4}}>{topicTitle}</h2><span className="badge">{topic.status==="published"?"PUBLISHED":"DRAFT"}</span></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className="btn secondary small" onClick={()=>setEditing(false)}>View</button><button className="btn secondary small" onClick={()=>setEditing(true)}>Edit</button><button className="btn secondary small" onClick={()=>setPreview(true)}>Preview</button></div></div><input className="input" value={topicTitle} onChange={e=>setTopicTitle(e.target.value)} style={{margin:"14px 0"}}/>
 {editing&&<div style={{display:"flex",gap:6,flexWrap:"wrap",padding:10,border:"1px solid var(--line)",borderBottom:0,borderRadius:"16px 16px 0 0",background:"var(--soft)"}}><select className="select" style={{width:120}} onChange={e=>format("formatBlock",e.target.value)} defaultValue="p"><option value="p">Paragraph</option><option value="h1">Title</option><option value="h2">Heading</option><option value="h3">Subheading</option></select><select className="select" style={{width:110}} onChange={e=>format("fontName",e.target.value)} defaultValue="Arial"><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Noto Sans</option><option>Noto Sans Devanagari</option></select><select className="select" style={{width:90}} onChange={e=>format("fontSize",e.target.value)} defaultValue="3"><option value="2">Small</option><option value="3">Normal</option><option value="4">Large</option><option value="5">XL</option><option value="6">XXL</option></select><Tool label="B" cmd="bold"/><Tool label="I" cmd="italic"/><Tool label="U" cmd="underline"/><Tool label="Text color" cmd="foreColor" value="#b91c1c"/><Tool label="Highlight" cmd="hiliteColor" value="#fff2a8"/><Tool label="• Bullets" cmd="insertUnorderedList"/><Tool label="1. Numbering" cmd="insertOrderedList"/><Tool label="↶" cmd="undo"/><Tool label="↷" cmd="redo"/><Tool label="←" cmd="justifyLeft"/><Tool label="↔" cmd="justifyCenter"/><Tool label="→" cmd="justifyRight"/></div>}
 <div ref={editor} contentEditable={editing} suppressContentEditableWarning onPaste={handlePaste} style={{minHeight:"62vh",padding:"30px clamp(18px,4vw,42px)",border:"1px solid var(--line)",borderRadius:editing?"0 0 18px 18px":"18px",background:"var(--card)",fontFamily:"Arial, Noto Sans Devanagari, sans-serif",fontSize:17,lineHeight:1.85,outline:"none",overflowWrap:"anywhere"}}/>
 <div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:16}}><button className="btn secondary" onClick={saveDraft} disabled={busy||!editing}>{busy?"SAVING…":"💾 SAVE TO DRAFTS"}</button><button className="btn primary" onClick={publish} disabled={busy}>{busy?"PUBLISHING…":"🌐 PUBLISH"}</button></div></section>}
 <section className="card"><h2>Draft & Published Library</h2><p className="muted">Only Published material is visible to students.</p>{subjects.map(s=><div key={s.id} style={{borderTop:"1px solid var(--line)",padding:"12px 0"}}><strong>{s.subject_name}</strong><div className="muted" style={{fontSize:12}}>{s.stage} · {s.paper} · {s.status}</div>{s.topics.map(t=><button key={t.id} className="topicRow" onClick={()=>openTopic(t)} style={{width:"100%",textAlign:"left",marginTop:7}}><strong>{t.title}</strong><span className="muted"> · {t.status}</span></button>)}</div>)}{!subjects.length&&<p className="muted">No study material yet.</p>}</section>
 </main>{preview&&<div style={{position:"fixed",inset:0,zIndex:50,background:"rgba(0,0,0,.55)",padding:"4vh 3vw",overflowY:"auto"}}><div className="card" style={{maxWidth:850,margin:"0 auto",minHeight:"90vh"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2>Student Preview</h2><button className="btn secondary" onClick={()=>setPreview(false)}>Close</button></div><article style={{marginTop:20,lineHeight:1.9,fontSize:18}} dangerouslySetInnerHTML={{__html:html()}}/></div></div>}</div>;
}