"use client";
import {useEffect,useState} from "react";

type Keyword={term:string;category:string;importance?:string};
type Block={type:"heading"|"subheading"|"paragraph"|"bullet"|"numbered"|"callout"|"table";text?:string;items?:string[];columns?:string[];rows?:string[][]};
type Sub={id:string;title:string;content:string;content_blocks?:Block[];important_keywords?:Keyword[]};

function renderBlocks(blocks:Block[]|undefined,fallback:string){
 const list=Array.isArray(blocks)&&blocks.length?blocks:[{type:"paragraph",text:fallback} as Block];
 return list.map((b,i)=>{
  const key="b-"+i;
  if(b.type==="heading")return <h2 key={key} style={{margin:"34px 0 12px",fontSize:"clamp(24px,5vw,31px)",lineHeight:1.25,fontWeight:850,letterSpacing:"-.02em"}}>{b.text}</h2>;
  if(b.type==="subheading")return <h3 key={key} style={{margin:"27px 0 9px",fontSize:"clamp(19px,4vw,23px)",lineHeight:1.35,fontWeight:800}}>{b.text}</h3>;
  if(b.type==="paragraph")return <p key={key} style={{margin:"0 0 17px",lineHeight:1.9}}>{b.text}</p>;
  if(b.type==="bullet")return <ul key={key} style={{margin:"4px 0 18px",paddingLeft:24}}>{(b.items||[]).map((x,j)=><li key={j} style={{marginBottom:9,lineHeight:1.75}}>{x}</li>)}</ul>;
  if(b.type==="numbered")return <ol key={key} style={{margin:"4px 0 18px",paddingLeft:27}}>{(b.items||[]).map((x,j)=><li key={j} style={{marginBottom:9,lineHeight:1.75}}>{x}</li>)}</ol>;
  if(b.type==="callout")return <aside key={key} style={{margin:"22px 0",padding:"16px 18px",borderLeft:"4px solid var(--accent)",borderRadius:"0 14px 14px 0",background:"var(--soft)",fontWeight:650,lineHeight:1.75}}>{b.text}</aside>;
  if(b.type==="table")return <div key={key} style={{overflowX:"auto",margin:"22px 0"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr>{(b.columns||[]).map((x,j)=><th key={j} style={{border:"1px solid var(--line)",padding:"10px",textAlign:"left",fontWeight:800}}>{x}</th>)}</tr></thead><tbody>{(b.rows||[]).map((row,j)=><tr key={j}>{row.map((x,k)=><td key={k} style={{border:"1px solid var(--line)",padding:"10px",verticalAlign:"top",lineHeight:1.55}}>{x}</td>)}</tr>)}</tbody></table></div>;
  return null;
 });
}

export default function ReaderControls({title,notes,contentBlocks,topicId,initialBookmarked,initialCompleted,subtopics}:{title:string;notes:string;contentBlocks?:Block[];topicId:string;initialBookmarked:boolean;initialCompleted:boolean;subtopics:Sub[]}) {
 const [marathi,setMarathi]=useState(false),[keyword,setKeyword]=useState<Keyword|null>(null),[explanation,setExplanation]=useState(""),[explaining,setExplaining]=useState(false),[showChapters,setShowChapters]=useState(false),[resume,setResume]=useState(0),[theme,setTheme]=useState<"light"|"paper"|"dark">("paper"),[fontScale,setFontScale]=useState(1),[bookmarked,setBookmarked]=useState(initialBookmarked),[bookmarking,setBookmarking]=useState(false),[completed,setCompleted]=useState(initialCompleted),[completing,setCompleting]=useState(false),[showSettings,setShowSettings]=useState(false),[progress,setProgress]=useState(0),[loading,setLoading]=useState(false),[keywordLoading,setKeywordLoading]=useState(false),[error,setError]=useState(""),[translated,setTranslated]=useState<any>(null),[readerSubtopics,setReaderSubtopics]=useState<Sub[]>(subtopics);

 useEffect(()=>{const saved=Number(localStorage.getItem("mpsc-progress-"+topicId)||0);setResume(saved);const onScroll=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;const pct=max>0?Math.min(100,Math.round(window.scrollY/max*100)):0;setProgress(pct);localStorage.setItem("mpsc-progress-"+topicId,String(pct));};window.addEventListener("scroll",onScroll);onScroll();return()=>window.removeEventListener("scroll",onScroll)},[topicId]);
 useEffect(()=>{if(readerSubtopics.length&&readerSubtopics.some(s=>!Array.isArray(s.important_keywords)||!s.important_keywords.length)){setKeywordLoading(true);fetch("/api/student/generate-keywords",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId})}).then(async x=>{const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not generate keywords.");if(Array.isArray(d.subtopics))setReaderSubtopics(prev=>prev.map((s,i)=>({...s,important_keywords:d.subtopics.find((x:any)=>x.id===s.id)?.important_keywords||s.important_keywords||[]})))}).catch(e=>setError(e?.message||"Could not generate keywords.")).finally(()=>setKeywordLoading(false))}},[topicId]);

 function continueReading(){window.scrollTo({top:Math.max(0,(document.documentElement.scrollHeight-window.innerHeight)*resume/100),behavior:"smooth"});}
 async function toggleBookmark(){if(bookmarking)return;const next=!bookmarked;setBookmarked(next);setBookmarking(true);try{const x=await fetch("/api/student/bookmark",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId,bookmarked:next})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not update bookmark.");setBookmarked(!!d.bookmarked)}catch(e:any){setBookmarked(!next);setError(e?.message||"Could not update bookmark")}finally{setBookmarking(false)}}
 async function explainKeyword(k:Keyword){setKeyword(k);setExplanation("");setExplaining(true);try{const context=notes+"\n"+readerSubtopics.map(s=>s.title+"\n"+s.content).join("\n");const x=await fetch("/api/student/explain-keyword",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keyword:k.term,context,language:marathi?"Marathi":"English"})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not prepare the explanation.");setExplanation(d.explanation||"")}catch(e:any){setExplanation(e?.message||"Could not prepare the explanation")}finally{setExplaining(false)}}
 async function markCompleted(){if(completing)return;setCompleting(true);try{const x=await fetch("/api/student/study-progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId,completed:!completed})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not update completion.");setCompleted(!!d.completed)}catch(e:any){setError(e?.message||"Could not update completion")}finally{setCompleting(false)}}
 async function translate(){if(translated){setMarathi(!marathi);return}setLoading(true);setError("");try{const x=await fetch("/api/student/translate-note",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,notes,subtopics:readerSubtopics})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Translation failed.");setTranslated(d.result);setMarathi(true)}catch(e:any){setError(e?.message||"Translation failed")}finally{setLoading(false)}}

 const data=marathi&&translated?translated:{title,notes,subtopics:readerSubtopics},bg=theme==="paper"?"#f7f0df":theme==="dark"?"#171717":"var(--card)",fg=theme==="dark"?"#eeeeee":"inherit";
 const bodyStyle={fontSize:`calc(clamp(17px,2vw,19px) * ${fontScale})`,color:fg};
 return <div style={{color:fg}}>
  <div style={{position:"sticky",top:0,zIndex:5,display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,padding:"10px 0",background:theme==="paper"?"rgba(247,240,223,.96)":theme==="dark"?"rgba(23,23,23,.96)":"var(--bg)",backdropFilter:"blur(10px)",borderBottom:"1px solid var(--line)"}}>
   <div style={{fontSize:12,fontWeight:850}}>READING · {progress}%</div><div style={{display:"flex",gap:6}}><button className="btn secondary" onClick={()=>setShowSettings(!showSettings)}>Aa</button><button className="btn secondary" onClick={()=>setShowChapters(!showChapters)}>☰</button><button className="btn secondary" onClick={toggleBookmark} disabled={bookmarking}>{bookmarking?"⏳":bookmarked?"🔖 Saved":"🔖"}</button></div>
  </div>
  {resume>5&&<button className="btn secondary" onClick={continueReading} style={{marginTop:8}}>▶ Continue Reading · {resume}%</button>}
  {showChapters&&<div style={{marginTop:10,padding:14,border:"1px solid var(--line)",borderRadius:14,background:bg}}><div style={{fontWeight:800,marginBottom:8}}>Chapter Navigation</div>{readerSubtopics.map((s,i)=><button key={s.id||i} className="btn secondary" style={{display:"block",width:"100%",textAlign:"left",marginTop:6}} onClick={()=>document.getElementById("sub-"+i)?.scrollIntoView({behavior:"smooth"})}>{i+1}. {s.title}</button>)}</div>}
  {showSettings&&<div style={{marginTop:10,padding:14,border:"1px solid var(--line)",borderRadius:14,background:bg}}><div style={{fontWeight:800,marginBottom:8}}>Reading Settings</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn secondary" onClick={()=>setFontScale(Math.max(.9,fontScale-.1))}>A−</button><button className="btn secondary" onClick={()=>setFontScale(Math.min(1.3,fontScale+.1))}>A+</button><button className="btn secondary" onClick={()=>setTheme("light")}>☀ Light</button><button className="btn secondary" onClick={()=>setTheme("paper")}>📜 Paper</button><button className="btn secondary" onClick={()=>setTheme("dark")}>🌙 Dark</button></div></div>}
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn primary" onClick={translate} disabled={loading}>{loading?"✨ Translating…":marathi?"ENGLISH":"✨ मराठी"}</button></div>
  {error&&<div className="error" style={{marginTop:10}}>{error}</div>}
  <article style={{marginTop:18,background:bg,border:theme==="paper"?"1px solid #e7dcc5":"1px solid var(--line)",borderRadius:24,padding:"clamp(24px,6vw,58px)",boxShadow:theme==="paper"?"0 12px 40px rgba(70,55,30,.08)":"0 8px 30px rgba(0,0,0,.04)"}}>
   <div style={{maxWidth:720,margin:"0 auto"}}>
    <div style={{fontSize:11,fontWeight:850,letterSpacing:".12em",textTransform:"uppercase",opacity:.58,marginBottom:10}}>MPSC STUDY READER</div>
    <h1 style={{fontSize:"clamp(30px,6vw,46px)",lineHeight:1.13,margin:"0 0 30px",letterSpacing:"-.025em"}}>{data.title}</h1>
    <div style={bodyStyle}>{renderBlocks((data as any).content_blocks?.length?(data as any).content_blocks:contentBlocks, data.notes)}</div>
    {data.subtopics?.map((s:Sub,i:number)=><section id={"sub-"+i} key={s.id||i} style={{marginTop:48,paddingTop:34,borderTop:"1px solid var(--line)"}}>
      <h2 style={{fontSize:"clamp(24px,5vw,32px)",lineHeight:1.25,margin:"0 0 20px",fontWeight:850}}>{i+1}. {s.title}</h2>
      <div style={bodyStyle}>{renderBlocks(s.content_blocks,s.content)}</div>
      <div style={{marginTop:24,padding:"15px 16px",borderRadius:15,background:theme==="dark"?"#242424":theme==="paper"?"#efe5d2":"rgba(20,70,120,.045)",border:"1px solid var(--line)"}}>
       <div style={{fontSize:12,fontWeight:900,letterSpacing:".04em",marginBottom:10}}>🔑 IMPORTANT MPSC KEYWORDS</div>
       <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{Array.isArray(s.important_keywords)&&s.important_keywords.length?s.important_keywords.map((k:Keyword,j:number)=><button key={k.term+j} className="btn secondary" style={{fontSize:12,fontWeight:700}} onClick={()=>explainKeyword(k)}>✨ {k.term}</button>):<span className="muted" style={{fontSize:13}}>{keywordLoading?"Preparing…":"No keywords available."}</span>}</div>
      </div>
    </section>)}
   </div>
  </article>
  <div style={{marginTop:22,padding:18,border:"1px solid var(--line)",borderRadius:18,background:bg,textAlign:"center"}}><div style={{fontWeight:900,fontSize:16}}>{completed?"✅ Notes Completed":"📖 Finished reading?"}</div><p className="muted" style={{margin:"6px 0 12px"}}>{completed?"This chapter is marked as completed.":"Mark this chapter completed after you finish reading it."}</p><button className={completed?"btn secondary":"btn primary"} onClick={markCompleted} disabled={completing}>{completing?"Saving…":completed?"✓ Marked Completed":"✓ MARK AS COMPLETED"}</button></div>
  {(keyword||explaining||explanation)&&<div style={{position:"fixed",inset:0,zIndex:20,background:"rgba(0,0,0,.52)",display:"flex",alignItems:"flex-end",justifyContent:"center"}} onClick={()=>{if(!explaining){setKeyword(null);setExplanation("")}}}><div style={{width:"min(760px,100%)",maxHeight:"82vh",overflowY:"auto",background:bg,color:fg,borderRadius:"24px 24px 0 0",padding:"24px 22px 30px",boxShadow:"0 -12px 45px rgba(0,0,0,.25)"}} onClick={e=>e.stopPropagation()}><div style={{width:42,height:4,borderRadius:4,background:"currentColor",opacity:.25,margin:"0 auto 18px"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}}><div><div style={{fontSize:11,fontWeight:800,opacity:.65,textTransform:"uppercase"}}>{keyword?.category||"Important term"}</div><h2 style={{margin:"4px 0 0",fontSize:26}}>✨ {keyword?.term}</h2></div><button className="btn secondary" onClick={()=>{setKeyword(null);setExplanation("")}}>×</button></div><div style={{marginTop:20,lineHeight:1.75,fontSize:16}}>{explaining?"✨ Preparing a source-based explanation…":explanation}</div></div></div>}
 </div>;
}
