"use client";
import {useEffect,useState} from "react";
type Keyword={term:string;category:string;importance?:string};
type Sub={id:string;title:string;content:string;important_keywords?:Keyword[]};
export default function ReaderControls({title,notes,topicId,initialBookmarked,initialCompleted,subtopics}:{title:string;notes:string;topicId:string;initialBookmarked:boolean;initialCompleted:boolean;subtopics:Sub[]}) {
 const [marathi,setMarathi]=useState(false),[keyword,setKeyword]=useState<Keyword|null>(null),[explanation,setExplanation]=useState(""),[explaining,setExplaining]=useState(false),[showChapters,setShowChapters]=useState(false),[resume,setResume]=useState(0),[theme,setTheme]=useState<"light"|"paper"|"dark">("light"),[fontScale,setFontScale]=useState(1),[bookmarked,setBookmarked]=useState(initialBookmarked),[bookmarking,setBookmarking]=useState(false),[completed,setCompleted]=useState(initialCompleted),[completing,setCompleting]=useState(false),[showSettings,setShowSettings]=useState(false),[progress,setProgress]=useState(0),[loading,setLoading]=useState(false),[keywordLoading,setKeywordLoading]=useState(false),[error,setError]=useState(""),[translated,setTranslated]=useState<any>(null),[readerSubtopics,setReaderSubtopics]=useState<Sub[]>(subtopics);
 useEffect(()=>{const saved=Number(localStorage.getItem("mpsc-progress-"+title)||0);setResume(saved);const onScroll=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;const pct=max>0?Math.min(100,Math.round(window.scrollY/max*100)):0;setProgress(pct);localStorage.setItem("mpsc-progress-"+title,String(pct));};window.addEventListener("scroll",onScroll);onScroll();return()=>window.removeEventListener("scroll",onScroll)},[title]);
 useEffect(()=>{if(readerSubtopics.length&&readerSubtopics.some(s=>!Array.isArray(s.important_keywords)||!s.important_keywords.length)){setKeywordLoading(true);fetch("/api/student/generate-keywords",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId})}).then(async x=>{const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not generate keywords.");if(Array.isArray(d.subtopics))setReaderSubtopics(d.subtopics)}).catch(e=>setError(e?.message||"Could not generate keywords.")).finally(()=>setKeywordLoading(false))}},[topicId]);
 function continueReading(){window.scrollTo({top:Math.max(0,(document.documentElement.scrollHeight-window.innerHeight)*resume/100),behavior:"smooth"});}
 async function toggleBookmark(){if(bookmarking)return;const next=!bookmarked;setBookmarked(next);setBookmarking(true);try{const x=await fetch("/api/student/bookmark",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId,bookmarked:next})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not update bookmark.");setBookmarked(!!d.bookmarked)}catch(e:any){setBookmarked(!next);setError(e?.message||"Could not update bookmark.")}finally{setBookmarking(false)}}
 async function explainKeyword(k:Keyword){setKeyword(k);setExplanation("");setExplaining(true);try{const context=notes+"\n"+readerSubtopics.map(s=>s.title+"\n"+s.content).join("\n");const x=await fetch("/api/student/explain-keyword",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keyword:k.term,context,language:marathi?"Marathi":"English"})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not prepare the explanation.");setExplanation(d.explanation||"")}catch(e:any){setExplanation(e?.message||"Could not prepare the explanation.")}finally{setExplaining(false)}}
 async function markCompleted(){if(completing)return;setCompleting(true);try{const x=await fetch("/api/student/study-progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId,completed:!completed})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Could not update completion.");setCompleted(!!d.completed)}catch(e:any){setError(e?.message||"Could not update completion.")}finally{setCompleting(false)}}
 async function translate(){if(translated){setMarathi(!marathi);return}setLoading(true);setError("");try{const x=await fetch("/api/student/translate-note",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,notes,subtopics:readerSubtopics})});const d=await x.json();if(!x.ok)throw new Error(d.error||"Translation failed.");setTranslated(d.result);setMarathi(true)}catch(e:any){setError(e?.message||"Translation failed.")}finally{setLoading(false)}}
 const data=marathi&&translated?translated:{title,notes,subtopics:readerSubtopics},bg=theme==="paper"?"#f5efdf":theme==="dark"?"#171717":"var(--card)",fg=theme==="dark"?"#e9e9e9":"inherit";
 return <div style={{color:fg}}>
  <div style={{position:"sticky",top:0,zIndex:5,display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,padding:"10px 0",background:theme==="paper"?"#f5efdf":theme==="dark"?"#171717":"var(--bg)",borderBottom:"1px solid var(--line)"}}>
   <div style={{fontSize:12,fontWeight:800}}>READING · {progress}%</div><div style={{display:"flex",gap:6}}>
    <button className="btn secondary" onClick={()=>setShowSettings(!showSettings)}>Aa</button><button className="btn secondary" onClick={()=>setShowChapters(!showChapters)}>☰</button><button className="btn secondary" onClick={toggleBookmark} disabled={bookmarking} title={bookmarked?"Remove bookmark":"Bookmark"}>{bookmarking?"⏳":bookmarked?"🔖 Saved":"🔖"}</button>
   </div>
  </div>
  {resume>5&&<button className="btn secondary" onClick={continueReading} style={{marginTop:8}}>▶ Continue Reading · {resume}%</button>}
  {keywordLoading&&<div style={{marginTop:10,padding:"10px 12px",borderRadius:12,background:"rgba(20,70,120,.05)",fontSize:13,fontWeight:700}}>✨ Preparing important MPSC keywords…</div>}
  {showChapters&&<div style={{marginTop:10,padding:14,border:"1px solid var(--line)",borderRadius:14,background:bg}}><div style={{fontWeight:800,marginBottom:8}}>Chapter Navigation</div>{readerSubtopics.map((s,i)=><button key={s.id||i} className="btn secondary" style={{display:"block",width:"100%",textAlign:"left",marginTop:6}} onClick={()=>document.getElementById("sub-"+i)?.scrollIntoView({behavior:"smooth"})}>{i+1}. {s.title}</button>)}</div>}
  {showSettings&&<div style={{marginTop:10,padding:14,border:"1px solid var(--line)",borderRadius:14,background:bg}}><div style={{fontWeight:800,marginBottom:8}}>Reading Settings</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn secondary" onClick={()=>setFontScale(Math.max(.9,fontScale-.1))}>A−</button><button className="btn secondary" onClick={()=>setFontScale(Math.min(1.3,fontScale+.1))}>A+</button><button className="btn secondary" onClick={()=>setTheme("light")}>☀ Light</button><button className="btn secondary" onClick={()=>setTheme("paper")}>📜 Paper</button><button className="btn secondary" onClick={()=>setTheme("dark")}>🌙 Dark</button></div></div>}
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn primary" onClick={translate} disabled={loading}>{loading?"✨ Translating…":marathi?"ENGLISH":"✨ मराठी"}</button>{translated&&<button className="btn secondary" onClick={()=>setMarathi(!marathi)}>{marathi?"Original English":"मराठी"}</button>}</div>{error&&<div className="error" style={{marginTop:10}}>{error}</div>}
  <article style={{marginTop:18,background:bg,border:"1px solid var(--line)",borderRadius:22,padding:"clamp(22px,5vw,54px)",boxShadow:"0 8px 30px rgba(0,0,0,.04)"}}>
   <h1 style={{fontSize:"clamp(30px,5vw,44px)",lineHeight:1.15,margin:"0 0 28px"}}>{data.title}</h1><div style={{fontSize:`calc(clamp(17px,2vw,19px) * ${fontScale})`,lineHeight:1.85,whiteSpace:"pre-wrap"}}>{data.notes}</div>
   {data.subtopics?.map((s:Sub,i:number)=><section id={"sub-"+i} key={s.id||i} style={{marginTop:42,paddingTop:30,borderTop:"1px solid var(--line)"}}><h2 style={{fontSize:"clamp(23px,4vw,30px)",lineHeight:1.3,margin:"0 0 18px"}}>{i+1}. {s.title}</h2><div style={{fontSize:`calc(clamp(17px,2vw,19px) * ${fontScale})`,lineHeight:1.85,whiteSpace:"pre-wrap"}}>{s.content}</div><div style={{marginTop:22,padding:"16px",borderRadius:16,background:theme==="dark"?"#242424":theme==="paper"?"#eee5d2":"rgba(20,70,120,.045)",border:"1px solid var(--line)"}}><div style={{fontSize:13,fontWeight:900,marginBottom:10}}>🔑 IMPORTANT KEYWORDS</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{Array.isArray(s.important_keywords)&&s.important_keywords.length?s.important_keywords.map((k:Keyword,j:number)=><button key={k.term+j} className="btn secondary" style={{fontSize:12,fontWeight:700}} onClick={()=>explainKeyword(k)}>✨ {k.term}</button>):<span className="muted" style={{fontSize:13}}>{keywordLoading?"Generating…":"No keywords available."}</span>}</div></div></section>)}
  </article>
  <div style={{marginTop:22,padding:18,border:"1px solid var(--line)",borderRadius:18,background:bg,textAlign:"center"}}><div style={{fontWeight:900,fontSize:16}}>{completed?"✅ Notes Completed":"📖 Finished reading?"}</div><p className="muted" style={{margin:"6px 0 12px"}}>{completed?"This chapter is marked as completed.":"Mark this chapter completed after you finish reading it."}</p><button className={completed?"btn secondary":"btn primary"} onClick={markCompleted} disabled={completing}>{completing?"Saving…":completed?"✓ Marked Completed":"✓ MARK AS COMPLETED"}</button></div>
  {(keyword||explaining||explanation)&&<div style={{position:"fixed",inset:0,zIndex:20,background:"rgba(0,0,0,.52)",display:"flex",alignItems:"flex-end",justifyContent:"center"}} onClick={()=>{if(!explaining){setKeyword(null);setExplanation("")}}}><div style={{width:"min(760px,100%)",maxHeight:"82vh",overflowY:"auto",background:bg,color:fg,borderRadius:"24px 24px 0 0",padding:"24px 22px 30px",boxShadow:"0 -12px 45px rgba(0,0,0,.25)"}} onClick={e=>e.stopPropagation()}><div style={{width:42,height:4,borderRadius:4,background:"currentColor",opacity:.25,margin:"0 auto 18px"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}}><div><div style={{fontSize:11,fontWeight:800,opacity:.65,textTransform:"uppercase"}}>{keyword?.category||"Important term"}</div><h2 style={{margin:"4px 0 0",fontSize:26}}>✨ {keyword?.term}</h2></div><button className="btn secondary" onClick={()=>{setKeyword(null);setExplanation("")}}>×</button></div><div style={{marginTop:20,whiteSpace:"pre-wrap",lineHeight:1.75,fontSize:16}}>{explaining?"✨ Preparing a source-based explanation…":explanation}</div></div></div>}
 </div>;
}