import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

export default async function Dashboard(){
 const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims)redirect("/login");
 const {data:profile}=await supabase.from("profiles").select("full_name,role,account_status").eq("id",data.claims.sub).single();if(!profile)redirect("/login");
 if(profile.role==="admin")redirect("/admin");
 if(profile.role==="teacher")redirect("/teacher");
 if(profile.account_status!=="active")return <div className="authWrap"><div className="card"><h2>Registration Pending</h2><p className="muted">Your account is awaiting Admin approval.</p></div></div>;
 const {count:totalTopics}=await supabase.from("study_topics").select("id",{count:"exact",head:true}).eq("status","published").eq("content_area","teacher");
 const {count:completedTopics}=await supabase.from("study_material_progress").select("id",{count:"exact",head:true}).eq("user_id",data.claims.sub);
 const total=totalTopics||0; const completed=completedTopics||0; const preparationProgress=total?Math.min(100,Math.round(completed/total*100)):0;
 return <div className="shell"><header className="topbar"><div className="topbarBrand"><img src="/mpsc-logo.png" className="brandLogo dashboardLogo" alt="MPSC ALL-IN-ONE"/></div><form action="/api/auth/signout" method="post"><button className="btn secondary">Logout</button></form></header><main className="main"><section className="dashboardHero"><div style={{fontSize:12,fontWeight:700,opacity:.8}}>GOOD TO SEE YOU 👋</div><h1 style={{margin:"6px 0",fontSize:27}}>Hello, {profile.full_name}</h1><p className="muted">Keep going! Your next milestone is within reach.</p><div style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,fontWeight:700,marginBottom:7}}><span>Preparation Progress</span><span>{preparationProgress}%</span></div><div className="progress"><span style={{width:`${preparationProgress}%`}}/></div></div></section><div className="quickGrid"><a href="/study-material" className="quickCard" style={{textDecoration:"none",color:"inherit"}}>{["📚","Study Material","Continue learning"].map(x=><div key={x}>{x}</div>)}</a>{[["🎯","Practice Tests","Test your knowledge"],["🎯","Practice Tests","Test your knowledge"],["📰","Current Affairs","Stay updated"],["🤖","AI Study Notes","Learn smarter"],["📊","Performance","Track your progress"],["🏆","Report Card","See your growth"]].map(([i,t,s])=>t==="AI Study Notes"?<a href="/ai-study-notes" className="quickCard" key={t} style={{textDecoration:"none",color:"inherit"}}><div className="quickIcon">{i}</div><strong>{t}</strong><div className="muted">{s}</div></a>:<div className="quickCard" key={t}><div className="quickIcon">{i}</div><strong>{t}</strong><div className="muted">{s}</div></div>)}</div></main><nav className="bottomNav"><a href="/dashboard">⌂<span>Home</span></a><a href="/dashboard">▣<span>Study</span></a><a href="/dashboard">◉<span>Tests</span></a><a href="/dashboard">•••<span>More</span></a></nav></div>;
}